import type { CheckReport, ServerWeighResult, SkillSetWeighResult } from "../core/types.js";
import type { CheckSkillResult } from "../check/check.js";
import type { WeighDiff } from "../weigh/diff.js";
import { VERSION } from "../version.js";

const SEV_LABEL = { error: "🔴 error", warn: "🟡 warn", info: "🔵 info" } as const;

function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function renderCheckMarkdown(report: CheckReport): string {
  const lines: string[] = [];
  lines.push(`## efaimo check (${report.surface}): grade ${report.grade.letter} (${report.grade.score})`);
  lines.push("");
  lines.push(`target: \`${report.target}\``);
  lines.push("");
  if (!report.findings.length) {
    lines.push("no findings. clean.");
  } else {
    lines.push("| severity | rule | finding |");
    lines.push("|---|---|---|");
    for (const f of report.findings) {
      lines.push(`| ${SEV_LABEL[f.severity]} | ${f.ruleId} | ${esc(f.message)} |`);
    }
  }
  lines.push("");
  for (const note of report.notes) lines.push(`> ${esc(note)}`);
  lines.push("");
  lines.push(
    `<sub>generated by [efaimo](https://github.com/efaimo-ai/efaimo) v${report.version} | [rule docs](https://github.com/efaimo-ai/efaimo/blob/main/docs/RULES.md)</sub>`,
  );
  return lines.join("\n");
}

export function renderSkillSetMarkdown(res: CheckSkillResult): string {
  const lines: string[] = [];
  lines.push(`## efaimo check: ${res.perSkill.length} Agent Skills`);
  lines.push("");
  lines.push("| skill | grade | errors | warnings | info |");
  lines.push("|---|---|---|---|---|");
  for (const s of [...res.perSkill].sort((a, b) => a.report.grade.score - b.report.grade.score)) {
    const c = s.report.counts;
    lines.push(`| \`${esc(s.name)}\` | ${s.report.grade.letter} (${s.report.grade.score}) | ${c.error} | ${c.warn} | ${c.info} |`);
  }
  if (res.setFindings.length) {
    lines.push("");
    lines.push("**Across the set**");
    for (const f of res.setFindings) lines.push(`- ${SEV_LABEL[f.severity]} ${f.ruleId}: ${esc(f.message)}`);
  }
  lines.push("");
  lines.push(`<sub>generated by [efaimo](https://github.com/efaimo-ai/efaimo) v${VERSION}</sub>`);
  return lines.join("\n");
}

export function renderWeighMarkdown(w: ServerWeighResult | SkillSetWeighResult): string {
  const lines: string[] = [];
  if (w.kind === "mcp") {
    lines.push(`## efaimo weigh: \`${w.label}\``);
    lines.push("");
    lines.push(`tools ${w.toolCount} | resources ${w.resourceCount} | prompts ${w.promptCount}`);
    lines.push("");
    lines.push("| serialization | tokens (o200k, est.) |");
    lines.push("|---|---|");
    lines.push(`| raw JSON | ${w.totals.rawJson.toLocaleString("en-US")} |`);
    lines.push(`| Claude-style | ${w.totals.claudeStyle.toLocaleString("en-US")} |`);
    lines.push(`| OpenAI tools | ${w.totals.openaiTools.toLocaleString("en-US")} |`);
    if (w.anthropicExactTotal !== undefined) {
      lines.push(`| anthropic exact (API) | ${w.anthropicExactTotal.toLocaleString("en-US")} |`);
    }
    lines.push("");
    if (w.perTool.length) {
      lines.push("| heaviest tools | tokens | desc | schema |");
      lines.push("|---|---|---|---|");
      for (const t of w.perTool.slice(0, 10)) {
        lines.push(`| \`${esc(t.name)}\` | ${t.tokens.claudeStyle} | ${t.descriptionTokens} | ${t.schemaTokens} |`);
      }
    }
  } else {
    lines.push(`## efaimo weigh (skills): \`${w.label}\``);
    lines.push("");
    lines.push("| skill | metadata (always) | body (on trigger) | lines | referenced files |");
    lines.push("|---|---|---|---|---|");
    for (const s of w.perSkill) {
      lines.push(
        `| \`${esc(s.name)}\` | ${s.metadataTokens} | ${s.bodyTokens} | ${s.bodyLines} | ${s.refFileCount ? `${s.refFileCount} (${s.refFileTokens} tok)` : "-"} |`,
      );
    }
    lines.push("");
    lines.push(
      `totals: metadata **${w.totals.metadata}** | body **${w.totals.body}** | referenced **${w.totals.refFiles}**`,
    );
  }
  lines.push("");
  for (const note of w.notes) lines.push(`> ${esc(note)}`);
  return lines.join("\n");
}

export function renderDiffMarkdown(d: WeighDiff): string {
  const sign = d.delta >= 0 ? "+" : "";
  const lines: string[] = [];
  lines.push(`## efaimo weigh diff`);
  lines.push("");
  lines.push(`Claude-style total: ${d.before.toLocaleString("en-US")} -> ${d.after.toLocaleString("en-US")} (**${sign}${d.delta.toLocaleString("en-US")}**, ${sign}${d.pct.toFixed(1)}%)`);
  if (d.toolChanges.length) {
    lines.push("");
    lines.push("| tool | before | after |");
    lines.push("|---|---|---|");
    for (const t of d.toolChanges.slice(0, 15)) {
      lines.push(`| \`${esc(t.name)}\` | ${t.before ?? "added"} | ${t.after ?? "removed"} |`);
    }
  }
  return lines.join("\n");
}
